### ISSUE TITLE
Folia

### ISSUE THREAD

**Issue by Branel** [LOOHP/LightUp#1]
Hello!

I love the concept of this plugin, and maybe you dont plan on maintaing it further, but I would just like to point out that it is marked as compatible with Folia on the Hangar website, but when I run it on my Folia server it gives me a warning that it is not marked as supporting Folia. I am running a newly compiled folia-bundler-1.21.4-R0.1-SNAPSHOT-reobf. 

Do you have any plans on making this compatible with Folia? 

P.S, your hangar redirect to your Github is currently "https://github.com/https://github.com/LOOHP", so had to find your github on your website. could be a good idea to resolve this too :)

Thanks.

**Comment by LOOHP** [comment]
Indeed it was wrongly marked as Folia supported. I do hope to support Folia in the future but since I personally don't use it yet and I don't see a lot of servers using it yet I'm not too motivated to support it yet (if it requires changing the logic of scheduling, such as in LightUp).

Thanks for telling me that the GitHub link on Hangar is wrong tho. Greatly appreciated.
